/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectobiblioteca;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author juans
 */
public class Interfaz extends javax.swing.JFrame {
    ConexionBD3 conex = new ConexionBD3();
    ArrayList<Cliente> clientes = new ArrayList();
    ArrayList<Libro> libros = new ArrayList();
    Cliente clienteLogin;
    
    public Interfaz() {
        
        
        
        libros.add(new Libro("El coronel no tiene quien le escriba", "1", "Harper", "Gabriel Garcia Márquez"));
        libros.add(new Libro("Crónica de una muerte anunciada", "2", "Santillana", "Gabriel Garcia Márquez"));
        libros.add(new Libro("Satanás", "3", "Seix Barral", "Mario Mendoza"));
        libros.add(new Libro("Scorpio City", "4", "Planeta", "Mario Mendoza"));
        libros.add(new Libro("Diario del fin del mundo", "5", "Planeta", "Mario Mendoza"));
        
        clientes = conex.cargarClientes(clientes);
        
       
        initComponents();
        setLocationRelativeTo(null);
        
        //Frame Menu
        FrameMenu.setSize(400, 300);
        FrameMenu.setLocationRelativeTo(null);
        
        //Frame Registro
        FrameRegistro.setSize(500,530);
        FrameRegistro.setLocationRelativeTo(null);
        
        
        //Frame Eliminar
        FrameEliminar.setSize(350, 200);
        FrameEliminar.setLocationRelativeTo(null);
        
        //Frame Editar
        FrameEditar.setSize(500,530);
        FrameEditar.setLocationRelativeTo(null);
        
        //Frame Pedir Libro
        FramePedirLibro.setSize(300, 250);
        FramePedirLibro.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FrameRegistro = new javax.swing.JFrame();
        lblNombreRegis = new javax.swing.JLabel();
        lblApellidosRegis = new javax.swing.JLabel();
        lblNumIdRegis = new javax.swing.JLabel();
        lblTipoIdRegis = new javax.swing.JLabel();
        lblDireccionRegis = new javax.swing.JLabel();
        lblEdadRegis = new javax.swing.JLabel();
        lblContraRegis = new javax.swing.JLabel();
        lblRepetirContraRegis = new javax.swing.JLabel();
        btnRegistrarse = new javax.swing.JButton();
        btnVolverRegis = new javax.swing.JButton();
        txtNombreRegis = new javax.swing.JTextField();
        txtApellidosRegis = new javax.swing.JTextField();
        txtEdadRegis = new javax.swing.JTextField();
        txtNumIdRegis = new javax.swing.JTextField();
        cmbTipoIdRegis = new javax.swing.JComboBox<>();
        txtDireccRegis = new javax.swing.JTextField();
        lblRegistrate = new javax.swing.JLabel();
        txtContraRegis = new javax.swing.JPasswordField();
        txtRepetirContraRegis = new javax.swing.JPasswordField();
        FrameEditar = new javax.swing.JFrame();
        lblNombreEdit = new javax.swing.JLabel();
        lblApellidosEdit = new javax.swing.JLabel();
        lblNumIdEdit = new javax.swing.JLabel();
        lblTipoIdEdit = new javax.swing.JLabel();
        lblDireccionEdit = new javax.swing.JLabel();
        lblEdadEdit = new javax.swing.JLabel();
        lblContraEdit = new javax.swing.JLabel();
        lblRepetirContraEdit = new javax.swing.JLabel();
        btnEditarEdit = new javax.swing.JButton();
        btnVolverEdit = new javax.swing.JButton();
        txtNombreEdit = new javax.swing.JTextField();
        txtApellidosEdit = new javax.swing.JTextField();
        txtEdadEdit = new javax.swing.JTextField();
        cmbTipoIdEdit = new javax.swing.JComboBox<>();
        txtDireccEdit = new javax.swing.JTextField();
        lblRegistrate1 = new javax.swing.JLabel();
        txtContraEdit = new javax.swing.JPasswordField();
        txtRepetirContraEdit = new javax.swing.JPasswordField();
        lblNumeroIdEdit = new javax.swing.JLabel();
        FrameEliminar = new javax.swing.JFrame();
        lblSeguro = new javax.swing.JLabel();
        btnSi = new javax.swing.JButton();
        btnVolverEliminar = new javax.swing.JButton();
        FramePedirLibro = new javax.swing.JFrame();
        lblISBN = new javax.swing.JLabel();
        txtISBN = new javax.swing.JTextField();
        btnPrestar = new javax.swing.JButton();
        btnVolverPrestar = new javax.swing.JButton();
        FrameMenu = new javax.swing.JFrame();
        lblBienvenidoMenu = new javax.swing.JLabel();
        lblNombreClieMenu = new javax.swing.JLabel();
        btnEditarMenu = new javax.swing.JButton();
        btnPedirLibroMenu = new javax.swing.JButton();
        btnEliminarMenu = new javax.swing.JButton();
        btnCerrarSesionMenu = new javax.swing.JButton();
        lblIdLogin = new javax.swing.JLabel();
        txtIdLogin = new javax.swing.JTextField();
        lblContraseñaLogin = new javax.swing.JLabel();
        btnIngresarLogin = new javax.swing.JButton();
        btnRegistrarseLogin = new javax.swing.JButton();
        txtContraseñaLogin = new javax.swing.JPasswordField();

        FrameRegistro.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        FrameRegistro.setTitle("Registro");

        lblNombreRegis.setText("Nombre:");

        lblApellidosRegis.setText("Apellidos:");

        lblNumIdRegis.setText("Numero de Identificación:");

        lblTipoIdRegis.setText("Tipo de identificación:");

        lblDireccionRegis.setText("Dirección:");

        lblEdadRegis.setText("Edad:");

        lblContraRegis.setText("Contraseña:");

        lblRepetirContraRegis.setText("Repetir contraseña:");

        btnRegistrarse.setText("Registrarse");
        btnRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarseActionPerformed(evt);
            }
        });

        btnVolverRegis.setText("Volver");
        btnVolverRegis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverRegisActionPerformed(evt);
            }
        });

        cmbTipoIdRegis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cedula de ciudadania", "Tarjeta de Identidad", "Pasaporte" }));
        cmbTipoIdRegis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoIdRegisActionPerformed(evt);
            }
        });

        lblRegistrate.setText("Registrate");

        javax.swing.GroupLayout FrameRegistroLayout = new javax.swing.GroupLayout(FrameRegistro.getContentPane());
        FrameRegistro.getContentPane().setLayout(FrameRegistroLayout);
        FrameRegistroLayout.setHorizontalGroup(
            FrameRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameRegistroLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(FrameRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FrameRegistroLayout.createSequentialGroup()
                        .addGroup(FrameRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreRegis)
                            .addComponent(lblRepetirContraRegis)
                            .addComponent(lblContraRegis)
                            .addComponent(lblApellidosRegis)
                            .addComponent(lblEdadRegis)
                            .addComponent(lblDireccionRegis)
                            .addComponent(lblTipoIdRegis)
                            .addComponent(lblNumIdRegis))
                        .addGap(24, 24, 24)
                        .addGroup(FrameRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombreRegis)
                            .addComponent(txtApellidosRegis)
                            .addComponent(txtEdadRegis)
                            .addComponent(txtNumIdRegis)
                            .addComponent(cmbTipoIdRegis, 0, 155, Short.MAX_VALUE)
                            .addComponent(txtDireccRegis)
                            .addComponent(txtContraRegis)
                            .addComponent(txtRepetirContraRegis)))
                    .addGroup(FrameRegistroLayout.createSequentialGroup()
                        .addComponent(btnRegistrarse)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVolverRegis)))
                .addGap(70, 70, 70))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FrameRegistroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblRegistrate)
                .addGap(209, 209, 209))
        );
        FrameRegistroLayout.setVerticalGroup(
            FrameRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameRegistroLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblRegistrate)
                .addGap(26, 26, 26)
                .addGroup(FrameRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNombreRegis)
                    .addComponent(txtNombreRegis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(FrameRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellidosRegis)
                    .addComponent(txtApellidosRegis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(FrameRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEdadRegis)
                    .addComponent(txtEdadRegis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(FrameRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumIdRegis)
                    .addComponent(txtNumIdRegis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(FrameRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoIdRegis)
                    .addComponent(cmbTipoIdRegis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(FrameRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDireccionRegis)
                    .addComponent(txtDireccRegis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(FrameRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContraRegis)
                    .addComponent(txtContraRegis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(FrameRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRepetirContraRegis)
                    .addComponent(txtRepetirContraRegis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(FrameRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarse)
                    .addComponent(btnVolverRegis))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        FrameEditar.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        FrameEditar.setTitle("Editar Info");

        lblNombreEdit.setText("Nombre:");

        lblApellidosEdit.setText("Apellidos:");

        lblNumIdEdit.setText("Numero de Identificación:");

        lblTipoIdEdit.setText("Tipo de identificación:");

        lblDireccionEdit.setText("Dirección:");

        lblEdadEdit.setText("Edad:");

        lblContraEdit.setText("Contraseña:");

        lblRepetirContraEdit.setText("Repetir contraseña:");

        btnEditarEdit.setText("Editar");
        btnEditarEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarEditActionPerformed(evt);
            }
        });

        btnVolverEdit.setText("Volver");
        btnVolverEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverEditActionPerformed(evt);
            }
        });

        cmbTipoIdEdit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cedula de ciudadania", "Tarjeta de Identidad", "Pasaporte" }));
        cmbTipoIdEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoIdEditActionPerformed(evt);
            }
        });

        lblRegistrate1.setText("Editar info");

        lblNumeroIdEdit.setText("id");

        javax.swing.GroupLayout FrameEditarLayout = new javax.swing.GroupLayout(FrameEditar.getContentPane());
        FrameEditar.getContentPane().setLayout(FrameEditarLayout);
        FrameEditarLayout.setHorizontalGroup(
            FrameEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameEditarLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(FrameEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FrameEditarLayout.createSequentialGroup()
                        .addGroup(FrameEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreEdit)
                            .addComponent(lblRepetirContraEdit)
                            .addComponent(lblContraEdit)
                            .addComponent(lblApellidosEdit)
                            .addComponent(lblEdadEdit)
                            .addComponent(lblDireccionEdit)
                            .addComponent(lblTipoIdEdit)
                            .addComponent(lblNumIdEdit))
                        .addGap(24, 24, 24)
                        .addGroup(FrameEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombreEdit)
                            .addComponent(txtApellidosEdit)
                            .addComponent(txtEdadEdit)
                            .addComponent(cmbTipoIdEdit, 0, 155, Short.MAX_VALUE)
                            .addComponent(txtDireccEdit)
                            .addComponent(txtContraEdit)
                            .addComponent(txtRepetirContraEdit)
                            .addComponent(lblNumeroIdEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(FrameEditarLayout.createSequentialGroup()
                        .addComponent(btnEditarEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVolverEdit)))
                .addGap(70, 70, 70))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FrameEditarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblRegistrate1)
                .addGap(209, 209, 209))
        );
        FrameEditarLayout.setVerticalGroup(
            FrameEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameEditarLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblRegistrate1)
                .addGap(26, 26, 26)
                .addGroup(FrameEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNombreEdit)
                    .addComponent(txtNombreEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(FrameEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellidosEdit)
                    .addComponent(txtApellidosEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(FrameEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEdadEdit)
                    .addComponent(txtEdadEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(FrameEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumIdEdit)
                    .addComponent(lblNumeroIdEdit))
                .addGap(18, 18, 18)
                .addGroup(FrameEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoIdEdit)
                    .addComponent(cmbTipoIdEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(FrameEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDireccionEdit)
                    .addComponent(txtDireccEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(FrameEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContraEdit)
                    .addComponent(txtContraEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(FrameEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRepetirContraEdit)
                    .addComponent(txtRepetirContraEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(FrameEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditarEdit)
                    .addComponent(btnVolverEdit))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        FrameEliminar.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        FrameEliminar.setTitle("Eliminar cliente");

        lblSeguro.setText("¿Esta seguro de que desea eliminar el usuario?");

        btnSi.setText("Si");
        btnSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiActionPerformed(evt);
            }
        });

        btnVolverEliminar.setText("Volver");

        javax.swing.GroupLayout FrameEliminarLayout = new javax.swing.GroupLayout(FrameEliminar.getContentPane());
        FrameEliminar.getContentPane().setLayout(FrameEliminarLayout);
        FrameEliminarLayout.setHorizontalGroup(
            FrameEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameEliminarLayout.createSequentialGroup()
                .addGroup(FrameEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(FrameEliminarLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(lblSeguro))
                    .addGroup(FrameEliminarLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(btnSi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVolverEliminar)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        FrameEliminarLayout.setVerticalGroup(
            FrameEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameEliminarLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(lblSeguro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(FrameEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSi)
                    .addComponent(btnVolverEliminar))
                .addGap(22, 22, 22))
        );

        FramePedirLibro.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        FramePedirLibro.setTitle("Pedir libro");

        lblISBN.setText("Ingrese el ISBN del libro");

        txtISBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtISBNActionPerformed(evt);
            }
        });

        btnPrestar.setText("Prestar");
        btnPrestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrestarActionPerformed(evt);
            }
        });

        btnVolverPrestar.setText("Volver");
        btnVolverPrestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverPrestarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FramePedirLibroLayout = new javax.swing.GroupLayout(FramePedirLibro.getContentPane());
        FramePedirLibro.getContentPane().setLayout(FramePedirLibroLayout);
        FramePedirLibroLayout.setHorizontalGroup(
            FramePedirLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FramePedirLibroLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnPrestar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVolverPrestar)
                .addGap(28, 28, 28))
            .addGroup(FramePedirLibroLayout.createSequentialGroup()
                .addGroup(FramePedirLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FramePedirLibroLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(lblISBN))
                    .addGroup(FramePedirLibroLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(txtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        FramePedirLibroLayout.setVerticalGroup(
            FramePedirLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FramePedirLibroLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(lblISBN)
                .addGap(18, 18, 18)
                .addComponent(txtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(FramePedirLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrestar)
                    .addComponent(btnVolverPrestar))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        FrameMenu.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        FrameMenu.setTitle("Menu cliente");

        lblBienvenidoMenu.setText("Bienvenid@");

        lblNombreClieMenu.setText("nombre");

        btnEditarMenu.setText("Editar Info");
        btnEditarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarMenuActionPerformed(evt);
            }
        });

        btnPedirLibroMenu.setText("Pedir Libro Prestado");
        btnPedirLibroMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedirLibroMenuActionPerformed(evt);
            }
        });

        btnEliminarMenu.setText("Eliminar usuario");
        btnEliminarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarMenuActionPerformed(evt);
            }
        });

        btnCerrarSesionMenu.setText("Cerrar Sesión");
        btnCerrarSesionMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FrameMenuLayout = new javax.swing.GroupLayout(FrameMenu.getContentPane());
        FrameMenu.getContentPane().setLayout(FrameMenuLayout);
        FrameMenuLayout.setHorizontalGroup(
            FrameMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCerrarSesionMenu)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FrameMenuLayout.createSequentialGroup()
                .addGroup(FrameMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FrameMenuLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(lblBienvenidoMenu))
                    .addGroup(FrameMenuLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(lblNombreClieMenu)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addGroup(FrameMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEliminarMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPedirLibroMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditarMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );
        FrameMenuLayout.setVerticalGroup(
            FrameMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameMenuLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(FrameMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBienvenidoMenu)
                    .addComponent(btnEditarMenu))
                .addGap(18, 18, 18)
                .addGroup(FrameMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreClieMenu)
                    .addComponent(btnPedirLibroMenu))
                .addGap(18, 18, 18)
                .addComponent(btnEliminarMenu)
                .addGap(34, 34, 34)
                .addComponent(btnCerrarSesionMenu)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblIdLogin.setText("Identificación:");

        lblContraseñaLogin.setText("Contraseña:");

        btnIngresarLogin.setText("Ingresar");
        btnIngresarLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarLoginActionPerformed(evt);
            }
        });

        btnRegistrarseLogin.setText("Registrarse");
        btnRegistrarseLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarseLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIdLogin)
                            .addComponent(lblContraseñaLogin))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIdLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                            .addComponent(txtContraseñaLogin)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnIngresarLogin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                        .addComponent(btnRegistrarseLogin)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdLogin)
                    .addComponent(txtIdLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContraseñaLogin)
                    .addComponent(txtContraseñaLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIngresarLogin)
                    .addComponent(btnRegistrarseLogin))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbTipoIdRegisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoIdRegisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoIdRegisActionPerformed

    private void cmbTipoIdEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoIdEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoIdEditActionPerformed

    private void txtISBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtISBNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtISBNActionPerformed

    private void btnIngresarLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarLoginActionPerformed
        clientes = conex.cargarClientes(clientes);
        String idLogin = txtIdLogin.getText();
        char[] contraseñaChar = txtContraseñaLogin.getPassword();
        String contraseña =  conex.contraseñaString(contraseñaChar) ;
        int band = 0;
        
        try {
            conex.stmt = conex.con.createStatement();
            conex.rs = conex.stmt.executeQuery("SELECT * FROM clientes");
            conex.rs.next();
            
            if(conex.rs.isFirst()== false){
                JOptionPane.showMessageDialog(null, "No hay ningun cliente registrado");
            }else{
                
                while(conex.rs.isAfterLast() == false){
                    if(idLogin.equals(conex.rs.getString("idCliente")) && contraseña.equals(conex.rs.getString("contraseña"))){
                        JOptionPane.showMessageDialog(null, "Bienvenido " + conex.rs.getString("nombre") + " " + conex.rs.getString("apellidos"));
                        
                        for(Cliente cliente:clientes){
                            if(cliente.getNumId().equals(idLogin) && cliente.getContraseña().equals(contraseña)){
                                clienteLogin = cliente;
                            }
                        }
                        
                        lblNombreClieMenu.setText(clienteLogin.getNombre() + " " + clienteLogin.getApellidos());
                        this.setVisible(false);
                        FrameMenu.setVisible(true);
                        band = 1;
                    }
                    conex.rs.next();
                }
                if(conex.rs.isAfterLast() == true && band == 0){
                    JOptionPane.showMessageDialog(null, "Ese cliente no esta registrado");
                }
            }
            
            conex.rs.close();
        } catch (SQLException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
            
        }
        
    }//GEN-LAST:event_btnIngresarLoginActionPerformed

    private void btnRegistrarseLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarseLoginActionPerformed
        clientes = conex.cargarClientes(clientes);
        txtNombreRegis.setText("");
        txtApellidosRegis.setText("");
        txtEdadRegis.setText("");
        txtContraRegis.setText("");
        txtRepetirContraRegis.setText("");
        txtDireccRegis.setText("");
        txtNumIdRegis.setText("");
        
        this.setVisible(false);
        FrameRegistro.setVisible(true);
        
    }//GEN-LAST:event_btnRegistrarseLoginActionPerformed

    private void btnVolverRegisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverRegisActionPerformed
        FrameRegistro.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_btnVolverRegisActionPerformed

    private void btnRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarseActionPerformed
        clientes = conex.cargarClientes(clientes);
        int edad = Integer.parseInt(txtEdadRegis.getText());
        char[] contraseñaChar = txtContraRegis.getPassword();
        char[] repetirContraChar = txtRepetirContraRegis.getPassword();
        String contraseña = conex.contraseñaString(contraseñaChar);
        String repetirContra = conex.contraseñaString(repetirContraChar);
        boolean estaCreado = false;
        
        for(Cliente cliente:clientes){
            if(cliente.getNumId().equals(txtNumIdRegis.getText())){
                estaCreado = true;
            }
        }
        
        if(estaCreado == true){
            JOptionPane.showMessageDialog(null, "Ya hay un cliente con esa identificación");
        }else{
            if(contraseña.equals(repetirContra)){
                
                conex.registroClientes(txtNumIdRegis.getText(), txtNombreRegis.getText(), txtApellidosRegis.getText(), cmbTipoIdRegis.getSelectedItem().toString(), edad, 
                    contraseña, txtDireccRegis.getText());

                clientes.add(new Cliente(txtNumIdRegis.getText(), txtNombreRegis.getText(), txtApellidosRegis.getText(), cmbTipoIdRegis.getSelectedItem().toString(), edad, 
                    contraseña, txtDireccRegis.getText()));
                
                FrameRegistro.setVisible(false);
                this.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(null, "La contraseña no coincide");
            }
        }
        clientes = conex.cargarClientes(clientes);
   
    }//GEN-LAST:event_btnRegistrarseActionPerformed

    private void btnEditarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarMenuActionPerformed
        clientes = conex.cargarClientes(clientes);
        txtNombreEdit.setText(clienteLogin.getNombre());
        txtApellidosEdit.setText(clienteLogin.getApellidos());
        txtEdadEdit.setText(String.valueOf(clienteLogin.getEdad()));
        txtDireccEdit.setText(clienteLogin.getDireccion());
        lblNumeroIdEdit.setText(clienteLogin.getNumId());
        
        FrameMenu.setVisible(false);
        FrameEditar.setVisible(true);
    }//GEN-LAST:event_btnEditarMenuActionPerformed

    private void btnEditarEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarEditActionPerformed
        clientes = conex.cargarClientes(clientes);
        int edad = Integer.parseInt(txtEdadEdit.getText());
        char[] contraseñaChar = txtContraEdit.getPassword();
        char[] repetirContraChar = txtRepetirContraEdit.getPassword();
        String contraseña = conex.contraseñaString(contraseñaChar);
        String repetirContra = conex.contraseñaString(repetirContraChar);
        boolean estaCreado = false;
        int i = 0;
        int index = 0;
        
        for(Cliente cliente:clientes){
            if(cliente.getNumId().equals(lblNumeroIdEdit.getText())){
                estaCreado = true;
                index = i;
            }
            i++;
        }
        
        if(estaCreado == true){
            System.out.println("Cliente encontrado");
            if(contraseña.equals(repetirContra)){
                
                conex.editarClientes(lblNumeroIdEdit.getText(), txtNombreEdit.getText(), txtApellidosEdit.getText(), cmbTipoIdEdit.getSelectedItem().toString(), edad, 
                    contraseña, txtDireccEdit.getText());
                
                clientes.get(index).setNombre(txtNombreEdit.getText());
                clientes.get(index).setApellidos(txtApellidosEdit.getText());
                clientes.get(index).setTipoId(cmbTipoIdEdit.getSelectedItem().toString());
                clientes.get(index).setEdad(edad);
                clientes.get(index).setContraseña(contraseña);
                clientes.get(index).setDireccion(txtDireccEdit.getText());

                FrameEditar.setVisible(false);
                FrameMenu.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(null, "La contraseña no coincide");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Cliente no encontrado");
        }
        
        clientes = conex.cargarClientes(clientes);
        lblNombreClieMenu.setText(txtNombreEdit.getText()+ " " + txtApellidosEdit.getText());
    }//GEN-LAST:event_btnEditarEditActionPerformed

    private void btnVolverEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverEditActionPerformed
        clientes = conex.cargarClientes(clientes);
        txtNombreEdit.setText("");
        txtApellidosEdit.setText("");
        txtEdadEdit.setText("");
        txtDireccEdit.setText("");
        lblNumeroIdEdit.setText("");
        
        FrameEditar.setVisible(false);
        FrameMenu.setVisible(true);
        
    }//GEN-LAST:event_btnVolverEditActionPerformed

    private void btnPedirLibroMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedirLibroMenuActionPerformed
        clientes = conex.cargarClientes(clientes);
        String librosLista = "";
        
        for(Libro libro:libros){
            librosLista = librosLista + libro.mostrarInfoLibros();
        }
        
        JOptionPane.showMessageDialog(null,"Elija el ISBN del libro que desee:\n" + librosLista);
        
        FrameMenu.setVisible(false);
        FramePedirLibro.setVisible(true);
    }//GEN-LAST:event_btnPedirLibroMenuActionPerformed

    private void btnEliminarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarMenuActionPerformed
        clientes = conex.cargarClientes(clientes);
        FrameMenu.setVisible(false);
        FrameEliminar.setVisible(true);
    }//GEN-LAST:event_btnEliminarMenuActionPerformed

    private void btnCerrarSesionMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionMenuActionPerformed
        JOptionPane.showMessageDialog(null, "Vuelva pronto :D");
        txtNombreRegis.setText("");
        txtApellidosRegis.setText("");
        txtEdadRegis.setText("");
        txtContraRegis.setText("");
        txtRepetirContraRegis.setText("");
        txtDireccRegis.setText("");
        txtNumIdRegis.setText("");
        txtIdLogin.setText("");
        txtContraseñaLogin.setText("");
        
        FrameMenu.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_btnCerrarSesionMenuActionPerformed

    private void btnVolverPrestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverPrestarActionPerformed
        clientes = conex.cargarClientes(clientes);
        FramePedirLibro.setVisible(false);
        FrameMenu.setVisible(true);
    }//GEN-LAST:event_btnVolverPrestarActionPerformed

    private void btnPrestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrestarActionPerformed
        clientes = conex.cargarClientes(clientes);
        conex.pedirLibroPrestado(clienteLogin.getNumId(), txtISBN.getText());
        
        FramePedirLibro.setVisible(false);
        FrameMenu.setVisible(true);
    }//GEN-LAST:event_btnPrestarActionPerformed

    private void btnSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiActionPerformed
        boolean estaCreado = false;
        int i = 0;
        int index = 0;
        
        for(Cliente cliente:clientes){
            if(cliente.getNumId().equals(clienteLogin.getNumId())){
                estaCreado = true;
                index = i;
            }
            i++;
        }
        
        conex.eliminarCliente(clienteLogin.getNumId());
        clientes.remove(index);
        
        clientes = conex.cargarClientes(clientes);
        FrameEliminar.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_btnSiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame FrameEditar;
    private javax.swing.JFrame FrameEliminar;
    private javax.swing.JFrame FrameMenu;
    private javax.swing.JFrame FramePedirLibro;
    private javax.swing.JFrame FrameRegistro;
    private javax.swing.JButton btnCerrarSesionMenu;
    private javax.swing.JButton btnEditarEdit;
    private javax.swing.JButton btnEditarMenu;
    private javax.swing.JButton btnEliminarMenu;
    private javax.swing.JButton btnIngresarLogin;
    private javax.swing.JButton btnPedirLibroMenu;
    private javax.swing.JButton btnPrestar;
    private javax.swing.JButton btnRegistrarse;
    private javax.swing.JButton btnRegistrarseLogin;
    private javax.swing.JButton btnSi;
    private javax.swing.JButton btnVolverEdit;
    private javax.swing.JButton btnVolverEliminar;
    private javax.swing.JButton btnVolverPrestar;
    private javax.swing.JButton btnVolverRegis;
    private javax.swing.JComboBox<String> cmbTipoIdEdit;
    private javax.swing.JComboBox<String> cmbTipoIdRegis;
    private javax.swing.JLabel lblApellidosEdit;
    private javax.swing.JLabel lblApellidosRegis;
    private javax.swing.JLabel lblBienvenidoMenu;
    private javax.swing.JLabel lblContraEdit;
    private javax.swing.JLabel lblContraRegis;
    private javax.swing.JLabel lblContraseñaLogin;
    private javax.swing.JLabel lblDireccionEdit;
    private javax.swing.JLabel lblDireccionRegis;
    private javax.swing.JLabel lblEdadEdit;
    private javax.swing.JLabel lblEdadRegis;
    private javax.swing.JLabel lblISBN;
    private javax.swing.JLabel lblIdLogin;
    private javax.swing.JLabel lblNombreClieMenu;
    private javax.swing.JLabel lblNombreEdit;
    private javax.swing.JLabel lblNombreRegis;
    private javax.swing.JLabel lblNumIdEdit;
    private javax.swing.JLabel lblNumIdRegis;
    private javax.swing.JLabel lblNumeroIdEdit;
    private javax.swing.JLabel lblRegistrate;
    private javax.swing.JLabel lblRegistrate1;
    private javax.swing.JLabel lblRepetirContraEdit;
    private javax.swing.JLabel lblRepetirContraRegis;
    private javax.swing.JLabel lblSeguro;
    private javax.swing.JLabel lblTipoIdEdit;
    private javax.swing.JLabel lblTipoIdRegis;
    private javax.swing.JTextField txtApellidosEdit;
    private javax.swing.JTextField txtApellidosRegis;
    private javax.swing.JPasswordField txtContraEdit;
    private javax.swing.JPasswordField txtContraRegis;
    private javax.swing.JPasswordField txtContraseñaLogin;
    private javax.swing.JTextField txtDireccEdit;
    private javax.swing.JTextField txtDireccRegis;
    private javax.swing.JTextField txtEdadEdit;
    private javax.swing.JTextField txtEdadRegis;
    private javax.swing.JTextField txtISBN;
    private javax.swing.JTextField txtIdLogin;
    private javax.swing.JTextField txtNombreEdit;
    private javax.swing.JTextField txtNombreRegis;
    private javax.swing.JTextField txtNumIdRegis;
    private javax.swing.JPasswordField txtRepetirContraEdit;
    private javax.swing.JPasswordField txtRepetirContraRegis;
    // End of variables declaration//GEN-END:variables
}
